version: 2
jobs:
  build:
    working_directory: ~/transmogrify
    docker:
      - image: circleci/clojure:lein-2.7.1
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: transmogrify-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: transmogrify-{{ checksum "project.clj" }}
      - run: lein do test, uberjar
      - store_artifacts:
          path: target/uberjar/transmogrify.jar
          destination: uberjar
dependencies:
  pre:
    # Install Leiningen as lein2
    - wget -O lein2 https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
    - chmod +x lein2
    - sudo mv lein2 /usr/local/bin
  override:
    - lein2 deps:
        pwd: cloverage
    - lein2 deps:
        pwd: lein-cloverage
test:
  override:
    - lein2 test:
        pwd: cloverage
    - lein2 test:
        pwd: lein-cloverage