version: 2
general:
  artifacts:
    - target/coverage
jobs:
  build:
    working_directory: ~/transmogrify
    docker:
      - image: circleci/clojure:lein-2.7.1
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: transmogrify-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: transmogrify-{{ checksum "project.clj" }}
      - run: lein do test, uberjar
      - store_artifacts:
          path: target/uberjar/transmogrify.jar
          destination: uberjar
test:
  override:
    - lein cloverage