version: 2
jobs:
  build:
    working_directory: ~/transmogrify
    docker:
      - image: circleci/clojure:lein-2.7.1
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: transmogrify-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: transmogrify-{{ checksum "project.clj" }}
      - run: lein do test, cloverage --codecov, uberjar
      - store_artifacts:
          path: target/uberjar/transmogrify.jar
          destination: uberjar
      - store_artifacts:
          path: target/coverage/
          destination: coverage
      - store_test_results:
          path: test/
      - run:
          command: |
            bash <(curl -s https://codecov.io/bash) -token $codecov -f ~/transmogrify/target/coverage/codecov.json
          when: on_success
