version: 2
jobs:
  build:
    working_directory: ~/transmogrify
    docker:
      - image: circleci/clojure:lein-2.7.1
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - transmogrify-{{ checksum "project.clj" }}
            - transmogrify
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: transmogrify-{{ checksum "project.clj" }}
      - run: lein do test, uberjar, cloverage --codecov
      - run:
          command: |

            bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -f target/coverage/codecov.json
          when: on_success
      - store_artifacts:
          path: target/uberjar/transmogrify-0.0.1-SNAPSHOT.jar
          destination: uberjar
      - store_artifacts:
          path: target/coverage/codecov.json
          destination: codecov
          when: on_success
      - store_test_results:
          path: test/

